safe: false
source: .
destination: ./_site
plugins_dir: ./_plugins
lsi: true
highlighter: rouge
markdown: kramdown
exclude: ['CNAME', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

url: 
baseurl: 

# Configuration for permalink
permalink: /:title.html

# Configuration for site
title: CS118 - Spring 2016 (UCLA)
description: 
author: Alexander Afanasyev
email:

# Configuration for navbar.html
navbar_list:
- name: Home
  link: /
- name: Syllabus
  link: /syllabus.html
- name: Homeworks
  link: /homeworks.html
- name: Project 1
  link: /project-1.html
- name: Project 2
  link: /project-2.html

#google_analytics:
#    account: UA-XXXXX-X

# pocket: true

# hatena: true
